### ISSUE TITLE
Did you find a solution to this error?

### ISSUE THREAD

**Issue by rsslldnphy** [mavbozo/shadow1#1]
Hi @mavbozo ! I've just encountered this exact error, and your repository is the only thing that comes up when I google for it. Did you ever find a solution to the problem?

Thanks!

**Comment by mavbozo** [comment]
@rsslldnphy yes, the workaround for this problem is by excluding lots of deps from fulcrologic/fulcro in :dependencies section on my shadow-cljs.edn file.

```
[fulcrologic/fulcro "2.8.12" :exclusions [org.clojure/clojurescript
                                                          org.clojure/core.async
                                                          org.clojure/google-closure-library
                                                          com.google.javascript/closure-compiler-externs]]
```

thomas heller the creator of shadow-cljs showed me this workaround in shadow-cljs slack channel.

it is related to the issue here https://github.com/fulcrologic/fulcro/issues/319

**Comment by rsslldnphy** [comment]
Thanks @mavbozo! That was a huge help.
